# Generated by Django 2.2.19 on 2021-02-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinguer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ipAddress', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PinguerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'Activation'), (2, 'Deactivation')], max_length=1)),
                ('event_date', models.DateField()),
                ('pinguer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIngueandoWebApp.Pinguer')),
            ],
        ),
    ]
