# Generated by Django 2.2.19 on 2021-02-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIngueandoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinguerevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Activation'), (2, 'Deactivation')]),
        ),
    ]
