# Generated by Django 2.2.19 on 2021-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIngueandoWebApp', '0002_auto_20210227_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinguerevent',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
